// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Demo scaffold generated by Token Launch Lab.
/// Production deployment requires ERC20 transfer wiring and full audit.
contract TokenVestingScaffold {
    address public immutable beneficiary;
    uint256 public immutable totalAllocation;
    uint256 public immutable cliffEnd;
    uint256 public immutable vestingEnd;

    constructor(address _beneficiary, uint256 _startTimestamp, uint256 _totalAllocation) {
        beneficiary = _beneficiary;
        totalAllocation = _totalAllocation;
        cliffEnd = _startTimestamp + 6 * 30 days;
        vestingEnd = cliffEnd + 24 * 30 days;
    }

    function vestedAmount(uint256 timestamp) public view returns (uint256) {
        if (timestamp < cliffEnd) return 0;
        if (timestamp >= vestingEnd) return totalAllocation;
        return (totalAllocation * (timestamp - cliffEnd)) / (vestingEnd - cliffEnd);
    }
}
